# Generated by Django 3.0.8 on 2020-07-30 02:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0003_auto_20200729_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 2, 28, 13, 285053, tzinfo=utc), verbose_name='date'),
        ),
    ]
