# Generated by Django 3.0.8 on 2020-07-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0005_auto_20200729_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
